INSERT INTO "JuridicShape" (code, level, designation) VALUES
('0', 1, 'Organisme de placement collectif en valeurs mobilières sans personnalité morale'),
('1', 1, 'Entrepreneur individuel'),
('2', 1, 'Groupement de droit privé non doté de la personnalité morale'),
('3', 1, 'Personne morale de droit étranger'),
('4', 1, 'Personne morale de droit public soumise au droit commercial'),
('5', 1, 'Société commerciale'),
('6', 1, 'Autre personne morale immatriculée au RCS'),
('7', 1, 'Personne morale et organisme soumis au droit administratif'),
('8', 1, 'Organisme privé spécialisé'),
('9', 1, 'Groupement de droit privé'),
('00', 2, 'Organisme de placement collectif en valeurs mobilières sans personnalité morale'),
('10', 2, 'Entrepreneur individuel'),
('21', 2, 'Indivision'),
('22', 2, 'Société créée de fait'),
('23', 2, 'Société en participation'),
('24', 2, 'Fiducie'),
('27', 2, 'Paroisse hors zone concordataire'),
('28', 2, 'Assujetti unique à la TVA'),
('29', 2, 'Autre groupement de droit privé non doté de la personnalité morale'),
('31', 2, 'Personne morale de droit étranger, immatriculée au RCS (registre du commerce et des sociétés)'),
('32', 2, 'Personne morale de droit étranger, non immatriculée au RCS'),
('41', 2, 'Etablissement public ou régie à caractère industriel ou commercial'),
('51', 2, 'Société coopérative commerciale particulière'),
('52', 2, 'Société en nom collectif'),
('53', 2, 'Société en commandite'),
('54', 2, 'Société à responsabilité limitée (SARL)'),
('55', 2, 'Société anonyme à conseil d''administration'),
('56', 2, 'Société anonyme à directoire'),
('57', 2, 'Société par actions simplifiée'),
('58', 2, 'Société européenne'),
('61', 2, 'Caisse d''épargne et de prévoyance'),
('62', 2, 'Groupement d''intérêt économique'),
('63', 2, 'Société coopérative agricole'),
('64', 2, 'Société d''assurance mutuelle'),
('65', 2, 'Société civile'),
('69', 2, 'Autre personne morale de droit privé inscrite au registre du commerce et des sociétés'),
('71', 2, 'Administration de l''état'),
('72', 2, 'Collectivité territoriale'),
('73', 2, 'Etablissement public administratif'),
('74', 2, 'Autre personne morale de droit public administratif'),
('81', 2, 'Organisme gérant un régime de protection sociale à adhésion obligatoire'),
('82', 2, 'Organisme mutualiste'),
('83', 2, 'Comité d''entreprise'),
('84', 2, 'Organisme professionnel'),
('85', 2, 'Organisme de retraite à adhésion non obligatoire'),
('91', 2, 'Syndicat de propriétaires'),
('92', 2, 'Association loi 1901 ou assimilé'),
('93', 2, 'Fondation'),
('99', 2, 'Autre personne morale de droit privé'),
('0000', 3, 'Organisme de placement collectif en valeurs mobilières sans personnalité morale'),
('1000', 3, 'Entrepreneur individuel'),
('2110', 3, 'Indivision entre personnes physiques'),
('2120', 3, 'Indivision avec personne morale'),
('2210', 3, 'Société créée de fait entre personnes physiques'),
('2220', 3, 'Société créée de fait avec personne morale'),
('2310', 3, 'Société en participation entre personnes physiques'),
('2320', 3, 'Société en participation avec personne morale'),
('2385', 3, 'Société en participation de professions libérales'),
('2400', 3, 'Fiducie'),
('2700', 3, 'Paroisse hors zone concordataire'),
('2800', 3, 'Assujetti unique à la TVA'),
('2900', 3, 'Autre groupement de droit privé non doté de la personnalité morale'),
('3110', 3, 'Représentation ou agence commerciale d''état ou organisme public étranger immatriculé au RCS'),
('3120', 3, 'Société commerciale étrangère immatriculée au RCS'),
('3205', 3, 'Organisation internationale'),
('3210', 3, 'État, collectivité ou établissement public étranger'),
('3220', 3, 'Société étrangère non immatriculée au RCS'),
('3290', 3, 'Autre personne morale de droit étranger'),
('4110', 3, 'Établissement public national à caractère industriel ou commercial doté d''un comptable public'),
('4120', 3, 'Établissement public national à caractère industriel ou commercial non doté d''un comptable public'),
('4130', 3, 'Exploitant public'),
('4140', 3, 'Établissement public local à caractère industriel ou commercial'),
('4150', 3, 'Régie d''une collectivité locale à caractère industriel ou commercial'),
('4160', 3, 'Institution Banque de France'),
('5191', 3, 'Société de caution mutuelle'),
('5192', 3, 'Société coopérative de banque populaire'),
('5193', 3, 'Caisse de crédit maritime mutuel'),
('5194', 3, 'Caisse (fédérale) de crédit mutuel'),
('5195', 3, 'Association coopérative inscrite (droit local Alsace Moselle)'),
('5196', 3, 'Caisse d''épargne et de prévoyance à forme coopérative'),
('5202', 3, 'Société en nom collectif'),
('5203', 3, 'Société en nom collectif coopérative'),
('5306', 3, 'Société en commandite simple'),
('5307', 3, 'Société en commandite simple coopérative'),
('5308', 3, 'Société en commandite par actions'),
('5309', 3, 'Société en commandite par actions coopérative'),
('5310', 3, 'Société en libre partenariat (SLP)'),
('5370', 3, 'Société de Participations Financières de Profession Libérale Société en commandite par actions (SPFPL SCA)'),
('5385', 3, 'Société d''exercice libéral en commandite par actions'),
('5410', 3, 'SARL nationale'),
('5415', 3, 'SARL d''économie mixte'),
('5422', 3, 'SARL immobilière pour le commerce et l''industrie (SICOMI)'),
('5426', 3, 'SARL immobilière de gestion'),
('5430', 3, 'SARL d''aménagement foncier et d''équipement rural (SAFER)'),
('5431', 3, 'SARL mixte d''intérêt agricole (SMIA)'),
('5432', 3, 'SARL d''intérêt collectif agricole (SICA)'),
('5442', 3, 'SARL d''attribution'),
('5443', 3, 'SARL coopérative de construction'),
('5451', 3, 'SARL coopérative de consommation'),
('5453', 3, 'SARL coopérative artisanale'),
('5454', 3, 'SARL coopérative d''intérêt maritime'),
('5455', 3, 'SARL coopérative de transport'),
('5458', 3, 'SARL coopérative de production (SCOP)'),
('5459', 3, 'SARL union de sociétés coopératives'),
('5460', 3, 'Autre SARL coopérative'),
('5470', 3, 'Société de Participations Financières de Profession Libérale Société à responsabilité limitée (SPFPL SARL)'),
('5485', 3, 'Société d''exercice libéral à responsabilité limitée'),
('5499', 3, 'Société à responsabilité limitée (sans autre indication)'),
('5505', 3, 'SA à participation ouvrière à conseil d''administration'),
('5510', 3, 'SA nationale à conseil d''administration'),
('5515', 3, 'SA d''économie mixte à conseil d''administration'),
('5520', 3, 'Fonds à forme sociétale à conseil d''administration'),
('5522', 3, 'SA immobilière pour le commerce et l''industrie (SICOMI) à conseil d''administration'),
('5525', 3, 'SA immobilière d''investissement à conseil d''administration'),
('5530', 3, 'SA d''aménagement foncier et d''équipement rural (SAFER) à conseil d''administration'),
('5531', 3, 'Société anonyme mixte d''intérêt agricole (SMIA) à conseil d''administration'),
('5532', 3, 'SA d''intérêt collectif agricole (SICA) à conseil d''administration'),
('5542', 3, 'SA d''attribution à conseil d''administration'),
('5543', 3, 'SA coopérative de construction à conseil d''administration'),
('5546', 3, 'SA de HLM à conseil d''administration'),
('5547', 3, 'SA coopérative de production de HLM à conseil d''administration'),
('5548', 3, 'SA de crédit immobilier à conseil d''administration'),
('5551', 3, 'SA coopérative de consommation à conseil d''administration'),
('5552', 3, 'SA coopérative de commerçants-détaillants à conseil d''administration'),
('5553', 3, 'SA coopérative artisanale à conseil d''administration'),
('5554', 3, 'SA coopérative (d''intérêt) maritime à conseil d''administration'),
('5555', 3, 'SA coopérative de transport à conseil d''administration'),
('5558', 3, 'SA coopérative de production  (SCOP) à conseil d''administration'),
('5559', 3, 'SA union de sociétés coopératives à conseil d''administration'),
('5560', 3, 'Autre SA coopérative à conseil d''administration'),
('5570', 3, 'Société de Participations Financières de Profession Libérale Société anonyme à conseil d''administration (SPFPL SA à conseil d''administration)'),
('5585', 3, 'Société d''exercice libéral à forme anonyme à conseil d''administration'),
('5599', 3, 'SA à conseil d''administration (s.a.i.)'),
('5605', 3, 'SA à participation ouvrière à directoire'),
('5610', 3, 'SA nationale à directoire'),
('5615', 3, 'SA d''économie mixte à directoire'),
('5620', 3, 'Fonds à forme sociétale à directoire'),
('5622', 3, 'SA immobilière pour le commerce et l''industrie (SICOMI) à directoire'),
('5625', 3, 'SA immobilière d''investissement à directoire'),
('5630', 3, 'Safer anonyme à directoire'),
('5631', 3, 'SA mixte d''intérêt agricole (SMIA)'),
('5632', 3, 'SA d''intérêt collectif agricole (SICA)'),
('5642', 3, 'SA d''attribution à directoire'),
('5643', 3, 'SA coopérative de construction à directoire'),
('5646', 3, 'SA de HLM à directoire'),
('5647', 3, 'Société coopérative de production de HLM anonyme à directoire'),
('5648', 3, 'SA de crédit immobilier à directoire'),
('5651', 3, 'SA coopérative de consommation à directoire'),
('5652', 3, 'SA coopérative de commerçants-détaillants à directoire'),
('5653', 3, 'SA coopérative artisanale à directoire'),
('5654', 3, 'SA coopérative d''intérêt maritime à directoire'),
('5655', 3, 'SA coopérative de transport à directoire'),
('5658', 3, 'SA coopérative de production (SCOP) à directoire'),
('5659', 3, 'SA union de sociétés coopératives à directoire'),
('5660', 3, 'Autre SA coopérative à directoire'),
('5670', 3, 'Société de Participations Financières de Profession Libérale Société anonyme à Directoire (SPFPL SA à directoire)'),
('5685', 3, 'Société d''exercice libéral à forme anonyme à directoire'),
('5699', 3, 'SA à directoire (s.a.i.)'),
('5710', 3, 'SAS, société par actions simplifiée'),
('5770', 3, 'Société de Participations Financières de Profession Libérale Société par actions simplifiée (SPFPL SAS)'),
('5785', 3, 'Société d''exercice libéral par action simplifiée'),
('5800', 3, 'Société européenne'),
('6100', 3, 'Caisse d''Épargne et de Prévoyance'),
('6210', 3, 'Groupement européen d''intérêt économique (GEIE)'),
('6220', 3, 'Groupement d''intérêt économique (GIE)'),
('6316', 3, 'Coopérative d''utilisation de matériel agricole en commun (CUMA)'),
('6317', 3, 'Société coopérative agricole'),
('6318', 3, 'Union de sociétés coopératives agricoles'),
('6411', 3, 'Société d''assurance à forme mutuelle'),
('6511', 3, 'Sociétés Interprofessionnelles de Soins Ambulatoires'),
('6521', 3, 'Société civile de placement collectif immobilier (SCPI)'),
('6532', 3, 'Société civile d''intérêt collectif agricole (SICA)'),
('6533', 3, 'Groupement agricole d''exploitation en commun (GAEC)'),
('6534', 3, 'Groupement foncier agricole'),
('6535', 3, 'Groupement agricole foncier'),
('6536', 3, 'Groupement forestier'),
('6537', 3, 'Groupement pastoral'),
('6538', 3, 'Groupement foncier et rural'),
('6539', 3, 'Société civile foncière'),
('6540', 3, 'Société civile immobilière'),
('6541', 3, 'Société civile immobilière de construction-vente'),
('6542', 3, 'Société civile d''attribution'),
('6543', 3, 'Société civile coopérative de construction'),
('6544', 3, 'Société civile immobilière d'' accession progressive à la propriété'),
('6551', 3, 'Société civile coopérative de consommation'),
('6554', 3, 'Société civile coopérative d''intérêt maritime'),
('6558', 3, 'Société civile coopérative entre médecins'),
('6560', 3, 'Autre société civile coopérative'),
('6561', 3, 'SCP d''avocats'),
('6562', 3, 'SCP d''avocats aux conseils'),
('6563', 3, 'SCP d''avoués d''appel'),
('6564', 3, 'SCP d''huissiers'),
('6565', 3, 'SCP de notaires'),
('6566', 3, 'SCP de commissaires-priseurs'),
('6567', 3, 'SCP de greffiers de tribunal de commerce'),
('6568', 3, 'SCP de conseils juridiques'),
('6569', 3, 'SCP de commissaires aux comptes'),
('6571', 3, 'SCP de médecins'),
('6572', 3, 'SCP de dentistes'),
('6573', 3, 'SCP d''infirmiers'),
('6574', 3, 'SCP de masseurs-kinésithérapeutes'),
('6575', 3, 'SCP de directeurs de laboratoire d''analyse médicale'),
('6576', 3, 'SCP de vétérinaires'),
('6577', 3, 'SCP de géomètres experts'),
('6578', 3, 'SCP d''architectes'),
('6585', 3, 'Autre société civile professionnelle'),
('6589', 3, 'Société civile de moyens'),
('6595', 3, 'Caisse locale de crédit mutuel'),
('6596', 3, 'Caisse de crédit agricole mutuel'),
('6597', 3, 'Société civile d''exploitation agricole'),
('6598', 3, 'Exploitation agricole à responsabilité limitée'),
('6599', 3, 'Autre société civile'),
('6901', 3, 'Autre personne de droit privé inscrite au registre du commerce et des sociétés'),
('7111', 3, 'Autorité constitutionnelle'),
('7112', 3, 'Autorité administrative ou publique indépendante'),
('7113', 3, 'Ministère'),
('7120', 3, 'Service central d''un ministère'),
('7150', 3, 'Service du ministère de la Défense'),
('7160', 3, 'Service déconcentré à compétence nationale d''un ministère (hors Défense)'),
('7171', 3, 'Service déconcentré de l''État à compétence (inter) régionale'),
('7172', 3, 'Service déconcentré de l''État à compétence (inter) départementale'),
('7179', 3, '(Autre) Service déconcentré de l''État à compétence territoriale'),
('7190', 3, 'Ecole nationale non dotée de la personnalité morale'),
('7210', 3, 'Commune et commune nouvelle'),
('7220', 3, 'Département'),
('7225', 3, 'Collectivité et territoire d''Outre Mer'),
('7229', 3, '(Autre) Collectivité territoriale'),
('7230', 3, 'Région'),
('7312', 3, 'Commune associée et commune déléguée'),
('7313', 3, 'Section de commune'),
('7314', 3, 'Ensemble urbain'),
('7321', 3, 'Association syndicale autorisée'),
('7322', 3, 'Association foncière urbaine'),
('7323', 3, 'Association foncière de remembrement'),
('7331', 3, 'Établissement public local d''enseignement'),
('7340', 3, 'Pôle métropolitain'),
('7341', 3, 'Secteur de commune'),
('7342', 3, 'District urbain'),
('7343', 3, 'Communauté urbaine'),
('7344', 3, 'Métropole'),
('7345', 3, 'Syndicat intercommunal à vocation multiple (SIVOM)'),
('7346', 3, 'Communauté de communes'),
('7347', 3, 'Communauté de villes'),
('7348', 3, 'Communauté d''agglomération'),
('7349', 3, 'Autre établissement public local de coopération non spécialisé ou entente'),
('7351', 3, 'Institution interdépartementale ou entente'),
('7352', 3, 'Institution interrégionale ou entente'),
('7353', 3, 'Syndicat intercommunal à vocation unique (SIVU)'),
('7354', 3, 'Syndicat mixte fermé'),
('7355', 3, 'Syndicat mixte ouvert'),
('7356', 3, 'Commission syndicale pour la gestion des biens indivis des communes'),
('7357', 3, 'Pôle d''équilibre territorial et rural (PETR)'),
('7361', 3, 'Centre communal d''action sociale'),
('7362', 3, 'Caisse des écoles'),
('7363', 3, 'Caisse de crédit municipal'),
('7364', 3, 'Établissement d''hospitalisation'),
('7365', 3, 'Syndicat inter hospitalier'),
('7366', 3, 'Établissement public local social et médico-social'),
('7367', 3, 'Centre Intercommunal d''action sociale (CIAS)'),
('7371', 3, 'Office public d''habitation à loyer modéré (OPHLM)'),
('7372', 3, 'Service départemental d''incendie et de secours (SDIS)'),
('7373', 3, 'Établissement public local culturel'),
('7378', 3, 'Régie d''une collectivité locale à caractère administratif'),
('7379', 3, '(Autre) Établissement public administratif local'),
('7381', 3, 'Organisme consulaire'),
('7382', 3, 'Établissement public national ayant fonction d''administration centrale'),
('7383', 3, 'Établissement public national à caractère scientifique culturel et professionnel'),
('7384', 3, 'Autre établissement public national d''enseignement'),
('7385', 3, 'Autre établissement public national administratif à compétence territoriale limitée'),
('7389', 3, 'Établissement public national à caractère administratif'),
('7410', 3, 'Groupement d''intérêt public (GIP)'),
('7430', 3, 'Établissement public des cultes d''Alsace-Lorraine'),
('7450', 3, 'Etablissement public administratif, cercle et foyer dans les armées'),
('7470', 3, 'Groupement de coopération sanitaire à gestion publique'),
('7490', 3, 'Autre personne morale de droit administratif'),
('8110', 3, 'Régime général de la Sécurité Sociale'),
('8120', 3, 'Régime spécial de Sécurité Sociale'),
('8130', 3, 'Institution de retraite complémentaire'),
('8140', 3, 'Mutualité sociale agricole'),
('8150', 3, 'Régime maladie des non-salariés non agricoles'),
('8160', 3, 'Régime vieillesse ne dépendant pas du régime général de la Sécurité Sociale'),
('8170', 3, 'Régime d''assurance chômage'),
('8190', 3, 'Autre régime de prévoyance sociale'),
('8210', 3, 'Mutuelle'),
('8250', 3, 'Assurance mutuelle agricole'),
('8290', 3, 'Autre organisme mutualiste'),
('8310', 3, 'Comité social économique d’entreprise'),
('8311', 3, 'Comité social économique d''établissement'),
('8410', 3, 'Syndicat de salariés'),
('8420', 3, 'Syndicat patronal'),
('8450', 3, 'Ordre professionnel ou assimilé'),
('8470', 3, 'Centre technique industriel ou comité professionnel du développement économique'),
('8490', 3, 'Autre organisme professionnel'),
('8510', 3, 'Institution de prévoyance'),
('8520', 3, 'Institution de retraite supplémentaire'),
('9110', 3, 'Syndicat de copropriété'),
('9150', 3, 'Association syndicale libre'),
('9210', 3, 'Association non déclarée'),
('9220', 3, 'Association déclarée'),
('9221', 3, 'Association déclarée d''insertion par l''économique'),
('9222', 3, 'Association intermédiaire'),
('9223', 3, 'Groupement d''employeurs'),
('9224', 3, 'Association d''avocats à responsabilité professionnelle individuelle'),
('9230', 3, 'Association déclarée, reconnue d''utilité publique'),
('9240', 3, 'Congrégation'),
('9260', 3, 'Association de droit local (Bas-Rhin, Haut-Rhin et Moselle)'),
('9300', 3, 'Fondation'),
('9900', 3, 'Autre personne morale de droit privé'),
('9970', 3, 'Groupement de coopération sanitaire à gestion privée');
